-- Supabase SQL Schema setup & migration for Kolfe Study
-- Copy and paste ALL of this into your Supabase SQL Editor (https://supabase.com/dashboard/project/_/sql) and click RUN.

-- 1. ADD 'date', 'file_url', and 'category' COLUMNS TO EXAMS TABLE
ALTER TABLE public.exams ADD COLUMN IF NOT EXISTS date TEXT;
ALTER TABLE public.exams ADD COLUMN IF NOT EXISTS file_url TEXT;
ALTER TABLE public.exams ADD COLUMN IF NOT EXISTS category TEXT DEFAULT 'school';

-- 2. CREATE EXAMS TABLE (if creating from scratch)
CREATE TABLE IF NOT EXISTS public.exams (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  subject TEXT NOT NULL,
  date TEXT NOT NULL,
  file_url TEXT,
  category TEXT DEFAULT 'school',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. CREATE BOOKS TABLE
CREATE TABLE IF NOT EXISTS public.books (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  author TEXT NOT NULL,
  category TEXT NOT NULL,
  file_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. CREATE NEWS TABLE
CREATE TABLE IF NOT EXISTS public.news (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  date TEXT NOT NULL,
  excerpt TEXT NOT NULL,
  file_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. CREATE STUDENT MESSAGES TABLE
CREATE TABLE IF NOT EXISTS public.student_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  subject TEXT NOT NULL,
  message TEXT NOT NULL,
  grade TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  subject TEXT NOT NULL,
  message TEXT NOT NULL,
  grade TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5b. CREATE CHALLENGE ATTEMPTS TABLE
CREATE TABLE IF NOT EXISTS public.challenge_attempts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_name TEXT NOT NULL,
  student_class TEXT,
  score INTEGER DEFAULT 0,
  total_questions INTEGER DEFAULT 10,
  answers JSONB DEFAULT '{}'::jsonb,
  status TEXT DEFAULT 'submitted',
  time_used_seconds INTEGER DEFAULT 0,
  submitted_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. CONFIGURE ROW LEVEL SECURITY (RLS) FOR MESSAGES AND OTHER TABLES
-- Disabling RLS allows public SELECT/INSERT/DELETE without policy blocking issues.
ALTER TABLE public.student_messages DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.exams DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.books DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.news DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.challenge_attempts DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.student_accounts DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.student_subscriptions DISABLE ROW LEVEL SECURITY;

-- Fallback explicitly policy definitions (if RLS is re-enabled in Supabase Dashboard)
DROP POLICY IF EXISTS "Public Full Access on student_messages" ON public.student_messages;
DROP POLICY IF EXISTS "Public Full Access on messages" ON public.messages;
DROP POLICY IF EXISTS "Public Full Access on exams" ON public.exams;
DROP POLICY IF EXISTS "Public Full Access on news" ON public.news;
DROP POLICY IF EXISTS "Public Full Access on books" ON public.books;
DROP POLICY IF EXISTS "Public Full Access on challenge_attempts" ON public.challenge_attempts;
DROP POLICY IF EXISTS "Public Full Access on student_accounts" ON public.student_accounts;
DROP POLICY IF EXISTS "Public Full Access on student_subscriptions" ON public.student_subscriptions;

CREATE POLICY "Public Select on student_messages" ON public.student_messages FOR SELECT TO public, anon, authenticated USING (true);
CREATE POLICY "Public Insert on student_messages" ON public.student_messages FOR INSERT TO public, anon, authenticated WITH CHECK (true);
CREATE POLICY "Public Delete on student_messages" ON public.student_messages FOR DELETE TO public, anon, authenticated USING (true);
CREATE POLICY "Public Select on challenge_attempts" ON public.challenge_attempts FOR SELECT TO public, anon, authenticated USING (true);
CREATE POLICY "Public Insert on challenge_attempts" ON public.challenge_attempts FOR INSERT TO public, anon, authenticated WITH CHECK (true);
CREATE POLICY "Public Delete on challenge_attempts" ON public.challenge_attempts FOR DELETE TO public, anon, authenticated USING (true);
CREATE POLICY "Public Select on student_accounts" ON public.student_accounts FOR SELECT TO public, anon, authenticated USING (true);
CREATE POLICY "Public Insert on student_accounts" ON public.student_accounts FOR INSERT TO public, anon, authenticated WITH CHECK (true);
CREATE POLICY "Public Update on student_accounts" ON public.student_accounts FOR UPDATE TO public, anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Public Select on student_subscriptions" ON public.student_subscriptions FOR SELECT TO public, anon, authenticated USING (true);
CREATE POLICY "Public Insert on student_subscriptions" ON public.student_subscriptions FOR INSERT TO public, anon, authenticated WITH CHECK (true);
CREATE POLICY "Public Update on student_subscriptions" ON public.student_subscriptions FOR UPDATE TO public, anon, authenticated USING (true) WITH CHECK (true);

-- 8. RELOAD POSTGREST SCHEMA CACHE (Fixes "Could not find column in schema cache" error)
NOTIFY pgrst, 'reload schema';

-- 9. INSERT INITIAL SAMPLE DATA
INSERT INTO public.exams (title, subject, date) VALUES
  ('Mathematics Final 2025', 'Math', 'June 2025'),
  ('Physics Midterm 2025', 'Physics', 'April 2025'),
  ('Chemistry Mock Exam', 'Chemistry', 'May 2025');

INSERT INTO public.books (title, author, category) VALUES
  ('Advanced Mathematics', 'Dr. Smith', 'Textbook'),
  ('Intro to Modern Physics', 'Prof. Einstein', 'Reference'),
  ('Organic Chemistry Guide', 'Dr. Polymer', 'Study Guide');

INSERT INTO public.news (title, date, excerpt) VALUES
  ('Science Fair 2026 Announced', 'Aug 15, 2026', 'Get ready to showcase your innovative projects at this year''s annual science fair.'),
  ('Library Renovation Complete', 'Aug 10, 2026', 'The new digital study pods and expanded reading areas are now open to all students.'),
  ('Upcoming Parent-Teacher Meetings', 'Aug 05, 2026', 'Schedule your slots for the mid-semester academic reviews.');
